# Generated by Django 4.2 on 2026-04-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_certification_id_alter_education_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resume_url',
            field=models.URLField(blank=True, help_text='URL to resume file'),
        ),
    ]
