# Generated by Django 4.2 on 2026-02-27 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_id_alter_jobcategory_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0007_applicationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='applicationmessage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savedjob',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=0, help_text='Overall match percentage')),
                ('skills_score', models.IntegerField(default=0, help_text='Skills match score')),
                ('experience_score', models.IntegerField(default=0, help_text='Experience match score')),
                ('education_score', models.IntegerField(default=0, help_text='Education match score')),
                ('location_score', models.IntegerField(default=0, help_text='Location match score')),
                ('matched_skills', models.JSONField(default=list, help_text='Skills that match')),
                ('missing_skills', models.JSONField(default=list, help_text='Skills candidate is missing')),
                ('matched_keywords', models.JSONField(default=list, help_text='Keywords that match')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('is_recommended', models.BooleanField(default=False, help_text='Recommended match (>70%)')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.job')),
            ],
            options={
                'ordering': ['-overall_score'],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
