# Generated by Django 4.2 on 2026-02-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_alter_interviewquestion_id_alter_mockinterview_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='A, B, C, or D', max_length=1),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation of the correct answer'),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='option_a',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='option_b',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='option_d',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('text', 'Text Answer')], default='mcq', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mockinterview',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='videointerview',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
